kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.69.2

- name: publish
  image: plugins/gh-release
  settings:
    pages_directory: public/

trigger:
  branch:
  - master
  event:
  - push
  - pull_request