baseURL = "https://cozi.dev/"
languageCode = "en-us"
title = "Cozi"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 10                 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10            # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = "cozi-dev"

enableEmoji = true

[taxonomies]
tag = "tags"

[author]
name = "kimcc"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
unsafe = true

[params]
math = false
# Blog description at the top of the homepage. Supports markdown.
description = "Cozi is a place where I share my software development journey."

showReadMore = false

# Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
enableKofi = false
kofi = ""

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1           # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 3

[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/archives/"
weight = 3

[[menu.main]]
name = "Hire me"
identifier = "hire-me"
url = "/hire-me/"
weight = 4

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true
