baseURL = "https://cozi.dev/"
languageCode = "en-us"
title = "Cozi"
theme = "cozi-modern"
enableRobotsTXT = true
paginate = 10                 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10            # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = "cozi-dev"

enableEmoji = true

[taxonomies]
tag = "tags"

[author]
name = "tungquach"
avatar = "images/author-avatar.jpg"
bio = "Software developer, writer, and open source enthusiast."
twitter = "@yourtwitterhandle"
github = "yourgithubhandle"
linkedin = "yourlinkedinprofile"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
unsafe = true

[params]
math = false
# Blog description at the top of the homepage. Supports markdown.
description = "Cozi is a place where I share my software development journey, exploring programming languages, frameworks, design patterns, and more."
# Main sections (currently used for the recent posts in the sidebar)
mainSections = ["posts"]

# Social media links displayed in footer
twitterURL = "https://twitter.com/yourtwitterhandle"
githubURL = "https://github.com/yourgithubhandle"
linkedinURL = "https://linkedin.com/in/yourlinkedinprofile"
rssURL = "/index.xml"

# Customize the homepage layout
showHero = true
showRecentPosts = true
showNewsletter = false
showSocialLinks = false

# Show / Hide elements in posts
showAuthor = true
showDate = true
showTags = true
showReadingTime = true
showShareButtons = true
showPrevNextLinks = true
showComments = true

# Appearance
# defaultTheme options are "light", "dark", "auto"
defaultTheme = "auto"

# Images for favicons
# apple_touch_icon = "apple-touch-icon.png"
# favicon_32 = "favicon-32x32.png"
# favicon_16 = "favicon-16x16.png"
# manifest_json = "site.webmanifest"

# Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
enableKofi = false
kofi = ""

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1           # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 4

[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/archives/"
weight = 5

[[menu.main]]
name = "Hire me"
identifier = "hire-me"
url = "/hire-me/"
weight = 6

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true
