baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cozi"
theme = "cupper-hugo-theme"
googleAnalytics = ''
disqusShortname = ''
enableGitInfo = false

[taxonomies]
tag = 'tags'

[permalinks]
post = '/:filename/'

[imaging]
quality = 99

[params]
description = 'COZI Jurney'
homeMetaContent = 'COZI Jurney'
footer = ''
dateFormat = 'Jan 2, 2006'
codePenUser = 'someUser'
katex = false
[[menu.nav]]
name = 'Home'
url = '/'
weight = 1

[[menu.nav]]
name = 'Blog'
url = '/post/'
weight = 2

[[menu.nav]]
name = 'Tags'
url = '/tags/'
weight = 3

[[menu.nav]]
name = 'About'
url = '/about/'
weight = 4

[[menu.nav]]
name = 'RSS'
url = '/index.xml'
weight = 5

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[markup.highlight]
codeFences = false
hl_Lines = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'monokai'
tabWidth = 4

[markup.tableOfContents]
endLevel = 6
startLevel = 2
